# SPDX-License-Identifier: LGPL-2.1-or-later
# needssslcertforbuild

[Include]
Include=mkosi-obs

[Config]
Profiles=netesp,desktop,flathub,kde,my-obs-sysupdate

[Content]
Packages=
        btrfs-progs
        dosfstools
        xfsprogs
        python-pefile
        cpio
        base-devel
        glibc
        linux
        dracut
        archlinux-keyring
        bpf
        ccid
        compsize
        cryptsetup
        dbus-broker-units
        expac
        git
        iproute2
        iputils
        libfido2
        linux
        man-db
        man-pages
        openssh
        pacman
        pcsclite
        perf
        polkit
        procps-ng
        psmisc
        python3
        qrencode
        sbsigntools
        shadow
        systemd-ukify
        tgt
        tpm2-tools
        tpm2-tss
        vim-minimal
        wget
        xz
        zram-generator


VolatilePackages=
        systemd-ukify

InitrdPackages=
        plymouth