# SPDX-License-Identifier: LGPL-2.1-or-later
# needssslcertforbuild

[Include]
Include=mkosi-obs

[Config]
Profiles=netesp,desktop,flathub,gnome,my-obs-sysupdate

[Content]
Packages=
        cpio
        base-devel
        glibc
        linux