# SPDX-License-Identifier: LGPL-2.1-or-later
# needssslcertforbuild

[Include]
Include=mkosi-obs

[Distribution]
Distribution=arch

[Config]
Profiles=netesp,desktop,flathub,kde,my-obs-sysupdate

[Content]
Packages=
        cpio
        base-devel
        glibc
        git
        rsync
        wget